apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092  # Add the default Kafka port
            - containerPort: 9093  # Add the INSIDE port for secure communication
          env:
            # Define the advertised listener
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://kafka:9093,PLAINTEXT://localhost:9092

            # Define the security protocol map
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT

            # Define the listener names
            - name: KAFKA_LISTENER_NAMES
              value: INSIDE,PLAINTEXT

            # Define the individual listeners
            - name: KAFKA_LISTENER_INTERNAL
              value: INSIDE://kafka:9093
            - name: KAFKA_LISTENER_OUTSIDE
              value: OUTSIDE://localhost:9093

            - name: KAFKA_LISTENER_PLAINTEXT
              value: PLAINTEXT://:9092  # Bind PLAINTEXT to port 9092

            # Define the listener security protocols
            - name: KAFKA_LISTENER_NAME_INSIDE_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_LISTENER_NAME_PLAINTEXT_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_LISTENER_INTERNAL_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_LISTENER_OUTSIDE_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_LISTENER_PLAINTEXT_SECURITY_PROTOCOL
              value: PLAINTEXT

            # Zookeeper connection
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
