apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092  # Default Kafka port
            - containerPort: 9093  # Internal communication port
          env:
            # Define the advertised listeners
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://localhost:9092,INSIDE://kafka:9093

            # Define the security protocol map
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,INSIDE:PLAINTEXT

            # Define the listener names
            - name: KAFKA_LISTENER_NAMES
              value: PLAINTEXT,INSIDE

            # Define the individual listeners
            - name: KAFKA_LISTENER_PLAINTEXT
              value: PLAINTEXT://0.0.0.0:9092  # Bind PLAINTEXT to port 9092

            - name: KAFKA_LISTENER_INSIDE
              value: INSIDE://0.0.0.0:9093  # Bind INSIDE to port 9093

            # Define the listener security protocols
            - name: KAFKA_LISTENER_NAME_PLAINTEXT_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_LISTENER_NAME_INSIDE_SECURITY_PROTOCOL
              value: PLAINTEXT

            # Zookeeper connection
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
